### ISSUE TITLE
Align Credentials Input to AWS

### ISSUE THREAD

**Issue by aaronfagan** [action-factory/aws-secrets-manager-action#8]
Hello,

Ive noticed that when using AWS provided Actions, credentials are passed like this:
```
aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
aws-region: ${{ secrets.AWS_REGION }}
```

Note the dashes - while here, they are passed with underscores:
```
aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
aws_secret_access_key: ${{ secrets.AWS_ACCESS_SECRET }}
aws_region: ${{ secrets.AWS_REGION }}
```

Wondering if it makes sense to align with the provider whose service is actually being used?

Thanks!

**Comment by aaronfagan** [comment]
Suggested fix - change `src/constants.ts` to: 
```
export enum Inputs {
  AWS_ACCESS_KEY_ID = 'aws-access-key-id',
  AWS_SECRET_ACCESS_KEY = 'aws-secret-access-key',
  AWS_REGION = 'aws-region',
  SECRETS = 'secrets',
  PARSE_JSON = 'parse-json'
}
```

**Comment by abhilash1in** [comment]
Makes sense. Feel free to submit a pull request 🙂 

If not, I'll get to this soon.

**Comment by aaronfagan** [comment]
PR Submitted: https://github.com/action-factory/aws-secrets-manager-action/pull/9

Thanks!
